"""Declared model family and leakage-safe prediction runner."""

from ifcred.models.bayesian import (
    BayesianFamilyTuningRun,
    BayesianModelResult,
    BayesianOptimizationSpec,
    BayesianSearchSpace,
    BayesianTrialResult,
    CategoricalDistribution,
    FloatDistribution,
    IntDistribution,
    recommended_bayesian_search_spaces,
    tune_model_family_bayesian,
)
from ifcred.models.registry import (
    DECLARED_MODEL_FAMILIES,
    ModelFamily,
    ModelSpec,
    build_classifier,
    validate_declared_family,
)
from ifcred.models.runner import (
    CalibrationMethod,
    CalibrationSpec,
    ModelFamilyRun,
    ModelPredictions,
    ModelTrainingData,
    PredictiveUtility,
    run_model_family,
    run_model_family_partitioned,
)
from ifcred.models.tuning import (
    CandidateCVResult,
    CrossValidationSpec,
    ModelFamilyTuningRun,
    ModelSearchSpace,
    ModelTuningResult,
    stratified_kfold_indices,
    tune_model_family,
)

__all__ = [
    "BayesianFamilyTuningRun",
    "BayesianModelResult",
    "BayesianOptimizationSpec",
    "BayesianSearchSpace",
    "BayesianTrialResult",
    "CalibrationMethod",
    "CalibrationSpec",
    "CandidateCVResult",
    "CrossValidationSpec",
    "CategoricalDistribution",
    "DECLARED_MODEL_FAMILIES",
    "ModelFamily",
    "ModelFamilyRun",
    "ModelFamilyTuningRun",
    "ModelPredictions",
    "ModelTrainingData",
    "ModelSearchSpace",
    "ModelSpec",
    "ModelTuningResult",
    "FloatDistribution",
    "IntDistribution",
    "PredictiveUtility",
    "build_classifier",
    "run_model_family",
    "run_model_family_partitioned",
    "recommended_bayesian_search_spaces",
    "stratified_kfold_indices",
    "tune_model_family",
    "tune_model_family_bayesian",
    "validate_declared_family",
]
